### ISSUE TITLE
create namespace & group

### ISSUE THREAD

**Issue by hashnao** [hashnao/gitops-practice#13]
### Description
以下のリソースを作成する Helm Charts を作成、ApplicationSet で設定する
* ~NS を作成~ 対応しない方針に変更 Cf. Change Log
* NS にグループに admin 権限を付与
* グループにユーザを追加

### ChangeLog
* [helper-operator](https://github.com/tjungbauer/openshift-cluster-bootstrap/tree/main/clusters/management-cluster/base-operators/charts/collection-management-operators/charts/helper-operator) で対応できる
* 複数の Charts を利用する際に Namespace の作成など values.yaml で重複するケースが多々あり、これを全て回収するのは非現実的なため
* [sources](https://github.com/argoproj/argo-cd/blob/master/docs/proposals/multiple-sources-for-applications.md) で単一の Application/ApplicationSet から複数の Charts を実行させるには便利だが、既存の Charts を利用する場合は特に参照している values.yaml 同士のコンフリクトが起きるため、デバッグが大変になる
```
kind: ApplicationSet
spec:
  generators:
    - git:
        files:
          - path: tenant-projects/**/values.yaml
        repoURL: "https://github.com/hashnao/gitops-practice"
        revision: main
  template:
    spec:
      sources:
      - repoURL: "https://github.com/hashnao/gitops-practice"
        targetRevision: main
        path: clusters/helper-proj-onboarding
        helm:
          valueFiles:
            - "/{{ .path.path }}/values.yaml"
            - /tenant-projects/values-global.yaml
      - repoURL: "https://github.com/hashnao/gitops-practice"
        targetRevision: main
        path: clusters/helper-operator
        helm:
          valueFiles:
            - "/{{ .path.path }}/values.yaml"
            - /tenant-projects/values-global.yaml
```

Reference:
* https://cloud.redhat.com/blog/project-onboarding-using-gitops-and-helm
  - <2> [preserveResourcesOnDeletion](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Application-Deletion/) を有効にして ApplicationSet が生成する  Application を残す ※デフォルトは削除される
  - <3> my-main-app や my-second-app の様に環境毎にディレクトリを作成して values.yaml を定義する i.e. [tenant-projects/my-main-app/cluster-local/values.yaml
](https://github.com/tjungbauer/openshift-cluster-bootstrap/blob/main/tenant-projects/my-main-app/cluster-local/values.yaml)
  - <6> で環境ごとの values.yaml を参照する
  - <7> が実行する [Helm Charts](https://github.com/tjungbauer/helm-charts/tree/main/charts/helper-proj-onboarding) で Chart.yaml](https://github.com/tjungbauer/openshift-cluster-bootstrap/blob/main/clusters/all/project-onboarding/Chart.yaml) に URL を定義している ※別の Git Repository に Helm Charts を配置している
```
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true # <2>
  generators:
    - git:
        files:
          - path: tenant-projects/**/values.yaml # <3>
        repoURL: 'https://github.com/tjungbauer/openshift-cluster-bootstrap'
        revision: main
  template:
    spec:
      source:
        helm:
          valueFiles: # <6>
            - '/{{ .path.path }}/values.yaml'
            - /tenant-projects/values-global.yaml
        path: clusters/all/project-onboarding
        repoURL: 'https://github.com/tjungbauer/openshift-cluster-bootstrap' # <7>
        targetRevision: main
```
  - ~Namespace 作成以外に Operator のインストールなど複数の Charts を単一の ApplicationSet で実行できるように [sources](https://github.com/argoproj/argo-cd/blob/master/docs/proposals/multiple-sources-for-applications.md) を加える~ -> 実施しない Cf. ChangeLog
