### ISSUE TITLE
camelk applicationset

### ISSUE THREAD

**Issue by hashnao** [hashnao/gitops-practice#69]
### Description
* グループを追加する際の ApplicationSet の変更例を加える
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test-camelk
  namespace: openshift-gitops
spec:
  goTemplate: true
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - git:
        files:
          - path: tenant-projects/camelk/*/values.yaml # tenant-projects/camelk/sample/values.yaml を配置する
        repoURL: "https://github.com/hashnao/gitops-practice"
        revision: main
    spec:
      project: default
      source:
        repoURL: "https://github.com/hashnao/gitops-practice"
        targetRevision: main
        path: clusters/helper-operator
        helm:
          valueFiles:
            - "/{{ .path.path }}/values.yaml" # Application CR が作成されると tenant-projects/camelk/sample/values.yaml が定義される
```
