### ISSUE TITLE
doc

### ISSUE THREAD

**Issue by hashnao** [hashnao/gitops-practice#75]
### Description
* ApplicationSet CR を最初 (PR をマージする前) に作成する ※ApplicationSet を作成 -> values.yaml を追加してマージする -> Camel K Operator がインストールされる流れが自然なので
* 新しいディレクトリに values.yaml を追加する PR のマージを契機にApplicationSet CR の Git Generator のパスを明示的に変更する必要はない https://github.com/hashnao/gitops-practice/commit/15ecfd7dbc2062f5a369e36f35e49c1016babbb9
```
 generators:
    - git:
        files:
          - path: tenant-projects/camelk/*/values.yaml
```
