### ISSUE TITLE
multiple namespaces

### ISSUE THREAD

**Issue by hashnao** [hashnao/gitops-practice#78]
複数の Namespace を対象に Camel K Operator をインストールする

**Comment by hashnao** [comment]
* values.yaml に複数を指定する -> camelk-test03 だけが作成される
```
operators:
  camelk-operator:
    enabled: true
    namespace:
      name: camelk-test02
      create: true
    subscription:
      channel: 1.10.x
      approval: Automatic
      operatorName: red-hat-camel-k
    operatorgroup:
      create: true
      notownnamespace: false
    nexus:
      mirror_url: http://nexusrepo-sonatype-nexus-service.dev-tool.svc.cluster.local:8081/repository/maven-public/
  camelk-operator:
    enabled: true
    namespace:
      name: camelk-test03
      create: true
    subscription:
      channel: 1.10.x
      approval: Automatic
      operatorName: red-hat-camel-k
    operatorgroup:
      create: true
      notownnamespace: false
    nexus:
      mirror_url: http://nexusrepo-sonatype-nexus-service.dev-tool.svc.cluster.local:8081/repository/maven-public/
```
* values.yaml operators.camelk-operator1, operators.camelk-operator2 の様にフィールドをユニークにする -> 成功
```
operators:
  camelk-operator1:
    enabled: true
    namespace:
      name: camelk-test04
      create: true
    subscription:
      operatorName: red-hat-camel-k
      channel: 1.10.x
      approval: Automatic
    operatorgroup:
      create: true
      notownnamespace: false
    nexus:
      mirror_url: http://nexusrepo-sonatype-nexus-service.dev-tool.svc.cluster.local:8081/repository/maven-public/
  camelk-operator2:
    enabled: true
    namespace:
      name: camelk-test05
      create: true
    subscription:
      operatorName: red-hat-camel-k
      channel: 1.10.x
      approval: Automatic
    operatorgroup:
      create: true
      notownnamespace: false
    nexus:
      mirror_url: http://nexusrepo-sonatype-nexus-service.dev-tool.svc.cluster.local:8081/repository/maven-public/
```
<img width="880" alt="Screenshot 2023-11-29 at 11 03 52" src="https://github.com/hashnao/gitops-practice/assets/1663165/cf12291a-fbbe-4095-8dcb-7a700ad52b06">
